#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0


bspc config border_width            2
bspc config window_gap              10

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config pointer_follows_focus   false
bspc config focus_follows_pointer   true

bspc rule -a TelegramDesktop desktop='^1'

bspc rule -a firefox desktop='^2'

bspc rule -a obsidian desktop='^3'

bspc rule -a Lutris desktop='^5'

bspc rule -a Steam desktop='^6'
bspc rule -a steam desktop='^6'
bspc rule -a steamwebhelper desktop='^6'

bspc rule -a retroarch desktop='^7'

bspc rule -a Gimp-2.10 desktop='^8'
bspc rule -a Blender desktop='^7'

bspc rule -a discord desktop='^9'

bspc rule -a qBittorrent desktop='^10'

bspc rule -a 'nvim' state=floating rectangle=800x550+558+262
bspc rule -a 'vimwiki' state=floating rectangle=1000x1000+475+60
bspc rule -a 'Picture-in-Picture' state=floating sticky=on
bspc rule -a TelegramDesktop state=floating


# Border
bspc config focused_border_color        "#5e81ac"
bspc config normal_border_color         "#4c566a"
bspc config active_border_color         "#d8dee9"


#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &

# start daemon for virtual audio cables
systemctl --user is-active --quiet virtual-audio-cables.service || systemctl --user start virtual-audio-cables.service

# Layout
setxkbmap -option grp:caps_toggle us,ru &

# Notifications
/usr/bin/dunst &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Wallpaper
feh --bg-fill --randomize $HOME/Pictures/wallpapers

# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Polybar
killall -q polybar
polybar
